### ISSUE TITLE
jslint 0.5 - incorrect modifier private

### ISSUE THREAD

**Issue by jhau** [millerjam/grails-jslint#12]
Hi,
when running grails 2.2.3 with version 0.5 of the jslint plugin I get the following error,

Error Error executing script Jslint: startup failed:
Jslint: 78: The class 'ReportsDslDelegate' has an incorrect modifier private.
 @ line 78, column 1.
1 error

is there any newer version of the plugin in the grails plugin repository with this problem fixed? 

thanks

Jeff

**Comment by beckje01** [comment]
It will be fixed in 0.6

**Comment by jhau** [comment]
thanks! is there any timeline for the 0.6 release?

**Comment by beckje01** [comment]
0.6 Was released today :cake:
