### ISSUE TITLE
indentation setting is ignored

### ISSUE THREAD

**Issue by c089** [millerjam/grails-jslint#4]
We use the following config line in an existing, non-grails project which uses the jslint4java ant task and jslint4java 2.0.2 (same as the plugin):

``` groovy
  jslint.options = 'browser,plusplus,regexp,sloppy,indent=4,nomen,maxerr=999999999,white'
```

However, jslint invoked through the grails plugin does not report indentation errors and stops after a few messages, despite the indent and maxerr settings.

**Comment by bendavieshe3** [comment]
I haven't tested any of the options nearly as much but some of them do seem ineffectual - I was passing that off to a weakness in the jslint4java library or my usage.

**Comment by beckje01** [comment]
@c089 I tested the options above on jslint.com; indent with white doesn't seem to work together. I have seen the max error work but if it isn't working for you can you send me a test js file I can run and see what's happening.

**Comment by c089** [comment]
Aaaah, it is stopping, but maxerr is not the culprit. Seems there is other ways to get jslint to stop ;) You're also right about indent depending on white - sorry about the invalid issue.
