### ISSUE TITLE
The type "JsLintConfig" is already defined (GGTS)

### ISSUE THREAD

**Issue by nolanlawson** [millerjam/grails-jslint#8]
I encountered [this bug](http://grails.1312388.n4.nabble.com/The-type-quot-JsLintConfig-quot-is-already-defined-in-GGTS-td4636030.html) when creating a JsLintConfig.groovy file in grails-app/conf, as explained by [the docs](http://www.grails.org/plugin/jslint).

I'm guessing this is actually a bug in GGTS and not the grails-jslint plugin, but I thought I'd bring this up just in case you had any ideas about it.  Thanks!

**Comment by beckje01** [comment]
If it would help I should be able to make the actual file name configurable. Would that solve the problem for you?

**Comment by nolanlawson** [comment]
Yes, I think that should solve the problem. Apparently there's a name collision with the default JsLintConfig class.

**Comment by beckje01** [comment]
I don't get the issue in Intillij, will look at this tonight.
