### ISSUE TITLE
Doesn't work with Grails/Groovy greater than 2.0

### ISSUE THREAD

**Issue by shin-nien** [millerjam/grails-jslint#9]
The private modifier needs to be removed from ReportsDslDelegate since top level private classes are not allowed anymore.

**Comment by behrangsa** [comment]
+1

**Comment by BertrandLF** [comment]
+1

**Comment by tompson** [comment]
+1

seem like the CodeNarc plugin hat the same issue: http://jira.grails.org/browse/GPCODENARC-33
